#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
  if [[ $file != .?* ]]; then
    filename_after_dash=${file#*-}
    echo "$filename_after_dash"
  fi
done
